[package]
name = "tus-cli"
description = "Command-line client for TUS uploads"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "tus"
path = "src/main.rs"

[dependencies]
tus-client = { workspace = true, features = ["source-file"] }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
figment = { workspace = true, features = ["env", "json", "toml", "yaml"] }
indicatif = "0.18"
parse-size = "1.1"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "net", "rt-multi-thread"] }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
tus-axum = { workspace = true }
tus-client = { workspace = true }
tus-protocol = { workspace = true, features = ["lock-memory", "state-memory", "storage-memory"] }

axum = { workspace = true }
tempfile = { workspace = true }
