[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1"
description = "TUS resumable upload protocol implementation for Rust"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sagikazarmark/tus-rs"
homepage = "https://github.com/sagikazarmark/tus-rs"
keywords = ["tus", "upload", "resumable", "http", "server"]
categories = ["web-programming::http-server", "network-programming", "asynchronous"]

[workspace.dependencies]
async-trait = "0.1"
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1" }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[workspace.metadata.release]
sign-commit = true
sign-tag = true
tag-message = "Release {{version}}"
tag-prefix = ""
