ignore = [".devenv", "target"]

[modules.tus]
source = "."
entrypoint = true

[modules.tests]
source = ".dagger/modules/tests"

settings.rustVersion = "1.98-slim-trixie"

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"

settings.version = "1.98-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

[modules.dang]
source = "github.com/sagikazarmark/daggerverse-beta/dang"
