[graph]
all-features = true

[licenses]
allow = [
  "Apache-2.0",
  "MIT",

  # Required by "unicode-ident"
  "Unicode-3.0",

  "BSD-3-Clause",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
