[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["shell"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
install-path = "CARGO_HOME"
install-updater = false

[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-22.04"
container = { image = "ghcr.io/blackdex/rust-musl:x86_64-musl-stable", host = "x86_64-unknown-linux-gnu" }
