[package]
name = "tus-hook-http"
description = "HTTP hook for the TUS protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tus-protocol = { workspace = true }

async-trait = { workspace = true }
hmac = "0.13"
reqwest = { workspace = true, default-features = false, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread"] }

[features]
default = ["reqwest/default"]
