[modules.demo]
source = "."
entrypoint = true

[modules.demo.settings]
rustVersion = "1.97-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

[modules.dagger-gha.settings]
lock = '"PINNED"'

[modules.wasm-pack]
source = "github.com/sagikazarmark/daggerverse-beta/wasm-pack"
check.skip = ["wasm-pack:test"]
