name = "demo"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!.devenv", "!.wrangler", "!build", "!dist", "!node_modules", "!target"]

[[dependencies]]
name = "dioxus"
source = "github.com/sagikazarmark/daggerverse-beta/dioxus"

[[dependencies]]
name = "tus"
source = "../"
