name = "demo"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!.devenv", "!assets", "!dist", "!node_modules", "!target"]

[[dependencies]]
name = "dioxus"
source = "github.com/sagikazarmark/daggerverse-beta/dioxus"

[[dependencies]]
name = "javascript-environment"
source = "github.com/sagikazarmark/daggerverse-beta/javascript-environment"

[[dependencies]]
name = "rust"
source = "github.com/sagikazarmark/daggerverse-beta/rust"

[[dependencies]]
name = "tus"
source = "../"
