name = "dioxus-tus-demo"
compatibility_date = "2026-07-14"

send_metrics = false
workers_dev = true
preview_urls = true

route = { pattern = "tus-demo.dioxus.cc", custom_domain = true, zone_name = "dioxus.cc" }

[assets]
directory = "dist/public"
not_found_handling = "single-page-application"
